# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Packages"
    url = "/packages/"
    weight = 1
    
[[main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[main]]
    name = "Blog"
    url = "https://blogs.rstudio.com/ai/"
    weight = 3


